name: Github-actions-hello-world-example
on: 
  push:
    branches: [master, dev]
jobs:
  uses-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.20.1'
      -
        name: install deps
        run: npm install 
      -
        name: run script
        run: node index.js
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - 
        name: list files
        run: ls -lah . 
  say-goodbye:
    runs-on: ubuntu-latest
    needs: [say-hello, uses-actions]
    steps:
      - 
        name: say-goodbye
        run: echo "say-hello and uses-actions is complete"
  