name: Github-actions-hello-world-example
jobs:
  say-hello:
    on: 
      push:
        branches: [dev]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Say Hello 
        run: echo "Hello world"
      -
        name: Do stuff
        run: |
          echo "Step 1"
          echo "step 2"
          echo "step 3"
      -
        name: Say Goodbye
        run: echo "goodbye"
  print-date:
    on: 
      pull_request:
        branches: [main]
    runs-on: ubuntu-latest
    steps:
      -
        name: 'print date'
        run: echo `date` on `uname -a`