name: Github-actions-hello-world-example
on: 
  push:
    branches: [master, dev]
env:
  COPY_DEST: '/tmp/copied'
jobs:
  uses-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.20.1'
      -
        name: install deps
        run: npm install 
      -
        name: run script
        run: node index.js
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - 
        name: list files
        run: ls -lah . 
  copy-files:
    runs-on: ubuntu-latest
    needs: list-files
    steps:
      - uses: actions/checkout@v2
      - 
        name: list files
        run: |
          echo $COPY_DEST
          mkdir -p $COPY_DEST
          cp . $COPY_DEST
  delete-files:
    runs-on: ubuntu-latest
    needs: copy-files
    steps:
      - 
        name: clean files 
        run: rm -rf $COPY_DEST
  say-goodbye:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [list-files, uses-actions, delete-files]
    steps:
      - 
        name: say-goodbye
        run: echo "say-hello and uses-actions is complete"
  